parameters:
    stripe_api_secret: '%env(STRIPE_API_SECRET)%'
    stripe_success_url: '%env(STRIPE_SUCCESS_URL)%'
    stripe_cancel_url: '%env(STRIPE_CANCEL_URL)%'

services:
    # Default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true  # Automatically registers your services as commands, event subscribers, etc.

    # Makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Service definition for StripeService
    App\Service\StripeService:
        arguments:
            $stripeApiSecret: '%stripe_api_secret%'

    # Service definition for CartService
    App\Service\CartService:
        arguments: 
            $sessionFactory: '@session.factory'

    # Register AccessDeniedListener
    App\EventListener\AccessDeniedListener:
        arguments:
            $logger: '@logger'  # Injecter le service logger
            $router: '@router'  # Injecter le service router
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: 'onKernelException' }  # Spécifiez la méthode
